nav:
  - Navigating These Notes:
    - "*"
  # - Unsorted:
  #     - "*"
  # - Lists:
  #     - "*"
  # - Terminology:
  #     - "*"
  # - Security\ Research:
  #     - "*"
  # - Challenges\ and\ CTFs\ ⚔️:
  #     - "*"
  # - NCAE\ 2025\ Preparation\ 🛡️:
  #     - "*"
  # - Works-in-Progress:
  #     - "*"
